# Generated by Django 4.2.14 on 2024-07-12 23:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('founders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=15)),
                ('website', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True)),
                ('logo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_listed', models.BooleanField(default=True)),
                ('is_boosted', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='founders.founder')),
            ],
        ),
    ]
